branches:
  - main

repositoryUrl: "git@github.com:garlicness/quand-manigancent-les-haricots.git"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# Quand Manigancent les haricots Changelog"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files: [src/Quand-manigancent-les-haricots.md]
          from: text:\ v\d+\.\d+\.\d+
          to: "text: v${nextRelease.version}"
          countMatches: true
          results:
            - file: src/Quand-manigancent-les-haricots.md
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/exec"
    - prepareCmd: make build
  - - "@semantic-release/github"
    - assets:
        - label: E-pub-book
          path: "./target/Quand_manigancent_les_haricots.epub"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "chore(release): perform release ${nextRelease.version}"
