name: EBook conversion
on:
  # Generates an artifact only on demand
  # Use the release action to generate an more official version
  workflow_dispatch:
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up context
        id: project_context
        uses: FranzDiebold/github-env-vars-action@v2
      - name: Extract tag
        id: branch_tag
        run: |
          echo ${{ github.ref }}
          branch=$(
          if [[ ${{ endsWith(github.ref, github.event.repository.default_branch) }} == true ]]; then
            echo nightly
          else
            echo ${{ env.CI_ACTION_REF_NAME_SLUG }}
          fi )
          echo "tag=${branch}" >> $GITHUB_OUTPUT
      - name: Write date
        run: |
          date=$(date -I)
          sed -i -e "s/date: XXXX-XX-XX/date: $date/" src/Quand-manigancent-les-haricots.md
      - name: Write commit SHA
        run: |
          sed -i -e "s/text: v0.0.0/text: ${{ env.CI_SHA_SHORT }}/" src/Quand-manigancent-les-haricots.md
      - name: Pandoc convert
        uses: docker://pandoc/core:2.18-ubuntu
        id: pandoc_convert
        with:
          args: '-o "Quand manigancent les haricots.epub" src/Quand-manigancent-les-haricots.md --css src/styles.css --toc --toc-depth=1'
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: epub-file-${{ steps.branch_tag.outputs.tag }}
          path: "Quand manigancent les haricots.epub"
