
name: EBook conversion
on: 
  push:
    branches: 
    - "*"
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: docker://pandoc/core:2.18-ubuntu
        with:
          args: "-o \"Quand manigancent les haricots.epub\" Quand-manigancent-les-haricots.md --css styles.css --toc --toc-depth=1"
      - uses: actions/upload-artifact@v3
        with:
          name: epub-file
          path: "Quand manigancent les haricots.epub"
